import arabidopsis from '@eplant/Species/arabidopsis'
import { PublicationViewerData } from '@eplant/views/PublicationViewer/types'
import { ViewProps } from '@eplant/View'

const a: ViewProps<PublicationViewerData> = {
  geneticElement: {
    id: 'AT3G24650',
    annotation: 'AP2/B3-like transcriptional factor family protein',
    species: arabidopsis,
    aliases: ['ABI3', 'AtABI3', 'SIS10'],
  },
  activeData: {
    publications: [
      {
        first_author: 'Alonso R',
        year: 2009,
        journal: 'Plant Cell',
        title:
          'A pivotal role of the basic leucine zipper transcription factor bZIP53 in the regulation of Arabidopsis seed maturation gene expression based on heterodimerization and protein complex formation.',
        pubmed_id: '19531597',
      },
      {
        first_author: 'Bassel GW',
        year: 2006,
        journal: 'J. Exp. Bot.',
        title:
          'ABI3 expression ceases following, but not during, germination of tomato and Arabidopsis seeds.',
        pubmed_id: '16531465',
      },
      {
        first_author: 'Bedi S',
        year: 2016,
        journal: 'Plant Sci.',
        title:
          'ABI3 mediates dehydration stress recovery response in Arabidopsis thaliana by regulating expression of downstream genes.',
        pubmed_id: '27457990',
      },
      {
        first_author: 'Bedi S',
        year: 2018,
        journal: 'FEBS Lett.',
        title:
          'Transcription factor ABI3 auto-activates its own expression during dehydration stress response.',
        pubmed_id: '30019436',
      },
      {
        first_author: 'Brady SM',
        year: 2003,
        journal: 'Plant J.',
        title:
          'The ABSCISIC ACID INSENSITIVE 3 (ABI3) gene is modulated by farnesylation and is involved in auxin signaling and lateral root development in Arabidopsis.',
        pubmed_id: '12662310',
      },
      {
        first_author: 'Brasil JN',
        year: 2015,
        journal: 'BMC Plant Biol.',
        title:
          'AIP1 is a novel Agenet/Tudor domain protein from Arabidopsis that interacts with regulators of DNA replication, transcription and chromatin remodeling.',
        pubmed_id: '26538092',
      },
      {
        first_author: 'Chen C',
        year: 2013,
        journal: 'J. Exp. Bot.',
        title:
          'Arabidopsis SAG protein containing the MDN1 domain participates in seed germination and seedling development by negatively regulating ABI3 and ABI5.',
        pubmed_id: '24163287',
      },
      {
        first_author: 'Cotter MQ',
        year: 2011,
        journal: 'Plant Signal Behav',
        title:
          'N-acylethanolamine (NAE) inhibits growth in Arabidopsis thaliana seedlings via ABI3-dependent and -independent pathways.',
        pubmed_id: '21633189',
      },
      {
        first_author: 'Dekkers BJ',
        year: 2016,
        journal: 'Plant J.',
        title:
          'The Arabidopsis DELAY OF GERMINATION 1 gene affects ABSCISIC ACID INSENSITIVE 5 (ABI5) expression and genetically interacts with ABI3 during Arabidopsis seed development.',
        pubmed_id: '26729600',
      },
      {
        first_author: 'Delmas F',
        year: 2013,
        journal: 'Proc. Natl. Acad. Sci. U.S.A.',
        title: "ABI3 controls embryo degreening through Mendel's I locus.",
        pubmed_id: '24043799',
      },
      {
        first_author: 'Ding ZJ',
        year: 2014,
        journal: 'Plant J.',
        title:
          'WRKY41 controls Arabidopsis seed dormancy via direct regulation of ABI3 transcript levels not downstream of ABA.',
        pubmed_id: '24946881',
      },
      {
        first_author: 'Efroni I',
        year: 2013,
        journal: 'Dev. Cell',
        title:
          'Regulation of leaf maturation by chromatin-mediated modulation of cytokinin responses.',
        pubmed_id: '23449474',
      },
      {
        first_author: 'Ezcurra I',
        year: 2000,
        journal: 'Plant J.',
        title:
          'Transactivation of the Brassica napus napin promoter by ABI3 requires interaction of the conserved B2 and B3 domains of ABI3 with different cis-elements: B2 mediates activation through an ABRE, whereas B3 interacts with an RY/G-box.',
        pubmed_id: '11029704',
      },
      {
        first_author: 'Feng CZ',
        year: 2014,
        journal: 'Plant J.',
        title:
          'Arabidopsis RAV1 transcription factor, phosphorylated by SnRK2 kinases, regulates the expression of ABI3, ABI4, and ABI5 during seed germination and early seedling development.',
        pubmed_id: '25231920',
      },
      {
        first_author: 'Gagete AP',
        year: 2009,
        journal: 'J. Exp. Bot.',
        title:
          'Functional analysis of the isoforms of an ABI3-like factor of Pisum sativum generated by alternative splicing.',
        pubmed_id: '19261920',
      },
      {
        first_author: 'Giraud E',
        year: 2009,
        journal: 'Plant Physiol.',
        title:
          'The transcription factor ABI4 is a regulator of mitochondrial retrograde expression of ALTERNATIVE OXIDASE1a.',
        pubmed_id: '19482916',
      },
      {
        first_author: 'Giraudat J',
        year: 1992,
        journal: 'Plant Cell',
        title: 'Isolation of the Arabidopsis ABI3 gene by positional cloning.',
        pubmed_id: '1359917',
      },
      {
        first_author: 'Holman TJ',
        year: 2009,
        journal: 'Proc. Natl. Acad. Sci. U.S.A.',
        title:
          'The N-end rule pathway promotes seed germination and establishment through removal of ABA sensitivity in Arabidopsis.',
        pubmed_id: '19255443',
      },
      {
        first_author: 'Hong J',
        year: 2019,
        journal: 'Plant Physiol. Biochem.',
        title:
          'ABSCISIC ACID-INSENSITIVE 3 is involved in brassinosteroid-mediated regulation of flowering in plants.',
        pubmed_id: '30908972',
      },
      {
        first_author: 'Kagaya Y',
        year: 2005,
        journal: 'Plant Cell Physiol.',
        title:
          'LEAFY COTYLEDON1 controls seed storage protein genes through its regulation of FUSCA3 and ABSCISIC ACID INSENSITIVE3.',
        pubmed_id: '15695450',
      },
      {
        first_author: 'Katagiri T',
        year: 2005,
        journal: 'Plant J.',
        title:
          'An important role of phosphatidic acid in ABA signaling during germination in Arabidopsis thaliana.',
        pubmed_id: '15960620',
      },
      {
        first_author: 'Klopffleisch K',
        year: 2011,
        journal: 'Mol. Syst. Biol.',
        title:
          'Arabidopsis G-protein interactome reveals connections to cell wall carbohydrates and morphogenesis.',
        pubmed_id: '21952135',
      },
      {
        first_author: 'Kotak S',
        year: 2007,
        journal: 'Plant Cell',
        title:
          'A novel transcriptional cascade regulating expression of heat stress proteins during seed development of Arabidopsis.',
        pubmed_id: '17220197',
      },
      {
        first_author: 'Kurup S',
        year: 2000,
        journal: 'Plant J.',
        title:
          'Interactions of the developmental regulator ABI3 with proteins identified from developing Arabidopsis seeds.',
        pubmed_id: '10743655',
      },
      {
        first_author: 'Lara P',
        year: 2003,
        journal: 'J. Biol. Chem.',
        title:
          'Synergistic activation of seed storage protein gene expression in Arabidopsis by ABI3 and two bZIPs related to OPAQUE2.',
        pubmed_id: '12657652',
      },
      {
        first_author: 'Lim S',
        year: 2013,
        journal: 'Plant Cell',
        title:
          'ABA-insensitive3, ABA-insensitive5, and DELLAs Interact to activate the expression of SOMNUS and other high-temperature-inducible genes in imbibed seeds in Arabidopsis.',
        pubmed_id: '24326588',
      },
      {
        first_author: 'Liu X',
        year: 2013,
        journal: 'Proc. Natl. Acad. Sci. U.S.A.',
        title:
          'Auxin controls seed dormancy through stimulation of abscisic acid signaling by inducing ARF-mediated ABI3 activation in Arabidopsis.',
        pubmed_id: '23986496',
      },
      {
        first_author: 'Mao Z',
        year: 2015,
        journal: 'J. Exp. Bot.',
        title:
          'Arabidopsis seed-specific vacuolar aquaporins are involved in maintaining seed longevity under the control of ABSCISIC ACID INSENSITIVE 3.',
        pubmed_id: '26019256',
      },
      {
        first_author: 'Mönke G',
        year: 2004,
        journal: 'Planta',
        title:
          'Seed-specific transcription factors ABI3 and FUS3: molecular interaction with DNA.',
        pubmed_id: '14767767',
      },
      {
        first_author: 'Mönke G',
        year: 2012,
        journal: 'Nucleic Acids Res.',
        title:
          'Toward the identification and regulation of the Arabidopsis thaliana ABI3 regulon.',
        pubmed_id: '22730287',
      },
      {
        first_author: 'Nakamura S',
        year: 2001,
        journal: 'Plant J.',
        title:
          'Physical interactions between ABA response loci of Arabidopsis.',
        pubmed_id: '11489176',
      },
      {
        first_author: 'Nakashima K',
        year: 2006,
        journal: 'Plant Mol. Biol.',
        title:
          'Transcriptional regulation of ABI3- and ABA-responsive genes including RD29B and RD29A in seeds, germinating embryos, and seedlings of Arabidopsis.',
        pubmed_id: '16463099',
      },
      {
        first_author: 'Nambara E',
        year: 1994,
        journal: 'Plant Cell Physiol.',
        title:
          'Isolation of an internal deletion mutant of the Arabidopsis thaliana ABI3 gene.',
        pubmed_id: '8055176',
      },
      {
        first_author: 'Nambara E',
        year: 2000,
        journal: 'Dev. Biol.',
        title:
          'The role of ABI3 and FUS3 loci in Arabidopsis thaliana on phase transition from late embryo development to germination.',
        pubmed_id: '10753527',
      },
      {
        first_author: 'Park J',
        year: 2011,
        journal: 'Plant Cell',
        title:
          'ABI3 and PIL5 collaboratively activate the expression of SOMNUS by directly binding to its promoter in imbibed Arabidopsis seeds.',
        pubmed_id: '21467583',
      },
      {
        first_author: 'Piskurewicz U',
        year: 2009,
        journal: 'EMBO J.',
        title:
          'Far-red light inhibits germination through DELLA-dependent stimulation of ABA synthesis and ABI3 activity.',
        pubmed_id: '19556968',
      },
      {
        first_author: 'Riechmann JL',
        year: 2000,
        journal: 'Curr. Opin. Plant Biol.',
        title: 'A genomic perspective on plant transcription factors.',
        pubmed_id: '11019812',
      },
      {
        first_author: 'Riechmann JL',
        year: 2000,
        journal: 'Science',
        title:
          'Arabidopsis transcription factors: genome-wide comparative analysis among eukaryotes.',
        pubmed_id: '11118137',
      },
      {
        first_author: 'Rohde A',
        year: 2000,
        journal: 'Plant Cell',
        title:
          'ABI3 affects plastid differentiation in dark-grown Arabidopsis seedlings.',
        pubmed_id: '10634906',
      },
      {
        first_author: 'Roscoe TT',
        year: 2015,
        journal: 'Plant Cell Physiol.',
        title:
          'Complementation of Seed Maturation Phenotypes by Ectopic Expression of ABSCISIC ACID INSENSITIVE3, FUSCA3 and LEAFY COTYLEDON2 in Arabidopsis.',
        pubmed_id: '25840088',
      },
      {
        first_author: 'Ryu H',
        year: 2014,
        journal: 'Nat Commun',
        title:
          'Control of early seedling development by BES1/TPL/HDA19-mediated epigenetic regulation of ABI3.',
        pubmed_id: '24938150',
      },
      {
        first_author: 'Salanoubat M',
        year: 2000,
        journal: 'Nature',
        title:
          'Sequence and analysis of chromosome 3 of the plant Arabidopsis thaliana.',
        pubmed_id: '11130713',
      },
      {
        first_author: 'Sasnauskas G',
        year: 2018,
        journal: 'FEBS J.',
        title:
          'DNA recognition by Arabidopsis transcription factors ABI3 and NGA1.',
        pubmed_id: '30183137',
      },
      {
        first_author: 'Uhrig JF',
        year: 2007,
        journal: 'Development',
        title:
          'The role of Arabidopsis SCAR genes in ARP2-ARP3-dependent cell morphogenesis.',
        pubmed_id: '17267444',
      },
      {
        first_author: 'Yang Y',
        year: 2011,
        journal: 'Plant Physiol.',
        title:
          'ABI4 activates DGAT1 expression in Arabidopsis seedlings during nitrogen deficiency.',
        pubmed_id: '21515696',
      },
      {
        first_author: 'Zhang X',
        year: 2005,
        journal: 'Genes Dev.',
        title:
          'The AIP2 E3 ligase acts as a novel negative regulator of ABA signaling by promoting ABI3 degradation.',
        pubmed_id: '15998807',
      },
    ],
    geneRIFs: [
      {
        publication: {
          pubmed_id: '15695450',
        },
        locus: 'AT3G24650',
        annotation:
          'We suggest that LEC1 controls the expression of the SSP genes in a hierarchical manner, which involves ABI3 and FUS3.',
      },
      {
        publication: {
          pubmed_id: '15960620',
        },
        locus: 'AT3G24650',
        annotation:
          'Double-mutant analysis showed that ABA-insensitive 4 (ABI4) is epistatic to AtLPP2 but ABA-insensitive 3 (ABI3) is not.',
      },
      {
        publication: {
          pubmed_id: '16463099',
        },
        locus: 'AT3G24650',
        annotation:
          'The expression of ABI3- and/or ABA-responsive genes and cis-elements in the promoters are discussed',
      },
      {
        publication: {
          pubmed_id: '16531465',
        },
        locus: 'AT3G24650',
        annotation:
          'ABI3 expression ceases following the completion of germination in both tomato and Arabidopsis seeds, suggesting that expression of this gene does not regulate germination.',
      },
      {
        publication: {
          pubmed_id: '17220197',
        },
        locus: 'AT3G24650',
        annotation:
          'ABSCISIC ACID-INSENSITIVE3 (ABI3) regulates the developmental expression of HsfA9.',
      },
      {
        publication: {
          pubmed_id: '19255443',
        },
        locus: 'AT3G24650',
        annotation:
          'PRT6 control of germination and establishment, as exemplified by ABA and sugar sensitivity, as well as storage oil mobilization, occurs at least in part via transcription factors ABI3 and ABI5.',
      },
      {
        publication: {
          pubmed_id: '19556968',
        },
        locus: 'AT3G24650',
        annotation:
          'We show that repression of germination by far-red light involves stabilized DELLA factors GAI, RGA and RGL2 that stimulate endogenous abscisic acid synthesis which, in turn, blocks germination through the transcription factor ABI3.',
      },
      {
        publication: {
          pubmed_id: '21467583',
        },
        locus: 'AT3G24650',
        annotation:
          'ABI3 and PIL5 collaboratively activate the expression of SOM mRNA by directly binding to and interacting with each other at the SOM promoter.',
      },
      {
        publication: {
          pubmed_id: '21633189',
        },
        locus: 'AT3G24650',
        annotation:
          'N-acylethanolamines may act to inhibit early seedling establishment by both ABI3-dependent and ABI3-independent pathways.',
      },
      {
        publication: {
          pubmed_id: '22730287',
        },
        locus: 'AT3G24650',
        annotation:
          'Identification of a set of 98 genes forming a basic ABI3 regulon.',
      },
      {
        publication: {
          pubmed_id: '23986496',
        },
        locus: 'AT3G24650',
        annotation:
          'Auxin controls seed dormancy through stimulation of abscisic acid signaling by inducing ARF-mediated ABI3 activation in Arabidopsis.',
      },
      {
        publication: {
          pubmed_id: '24043799',
        },
        locus: 'AT3G24650',
        annotation: "ABI3 controls embryo degreening through Mendel's I locus.",
      },
      {
        publication: {
          pubmed_id: '24163287',
        },
        locus: 'AT3G24650',
        annotation:
          'The function of AtSAG in abscisic acid (ABA)signalling depended on ABI3 and ABI5. AtSAG is an important negative regulator of ABA signalling during seed germination and seedling development.',
      },
      {
        publication: {
          pubmed_id: '24938150',
        },
        locus: 'AT3G24650',
        annotation:
          'The BES1-TPL-HDA19 repressor complex controls epigenetic silencing of ABI3 and thereby suppresses the abscisic acid signalling output during early seedling development.',
      },
      {
        publication: {
          pubmed_id: '24946881',
        },
        locus: 'AT3G24650',
        annotation:
          'WRKY41 is an important regulator of ABI3 expression, and hence of seed dormancy.',
      },
      {
        publication: {
          pubmed_id: '25231920',
        },
        locus: 'AT3G24650',
        annotation:
          'RAV1 plays an important role in abscisic acid signaling by modulating the expression of ABI3, ABI4, and AbI5 during seed germination and early seedling development.',
      },
      {
        publication: {
          pubmed_id: '25840088',
        },
        locus: 'AT3G24650',
        annotation:
          'This study examined the role of ABSCISIC ACID INSENSITIVE3 (ABI3), FUSCA3 (FUS3) and LEAFY COTYLEDON2 (LEC2), in the production of seed reserves in Arabidopsis.',
      },
      {
        publication: {
          pubmed_id: '26019256',
        },
        locus: 'AT3G24650',
        annotation:
          'TIP3;1 and TIP3;2 promoters could be activated by ABI3 in the presence of abscisic acid (ABA) in Arabidopsis protoplasts. TIP3 proteins were detected in protoplasts transiently expressing ABI3 and in ABI3-overexpressing seedlings treated with ABA.',
      },
      {
        publication: {
          pubmed_id: '26538092',
        },
        locus: 'AT3G24650',
        annotation:
          'AIP1 interacts with ABAP1, with a plant histone modification "reader" (LHP1) and with non modified histones. Also, expression of ABAP1 and LHP1 target genes were repressed in flower buds of plants with reduced levels of AIP1.',
      },
      {
        publication: {
          pubmed_id: '26729600',
        },
        locus: 'AT3G24650',
        annotation:
          'The abi3-1 dog1-1 double mutant produced green seeds which are highly abscisic acid (ABA) insensitive, phenocopying severe abi3 mutants, indicating that dog1-1 acts as an enhancer of the weak abi3-1 allele and thus revealing a genetic interaction between both genes.',
      },
      {
        publication: {
          pubmed_id: '27457990',
        },
        locus: 'AT3G24650',
        annotation:
          'ABI3 mediates dehydration stress signaling in Arabidopsis through regulation of a group of genes that play a role primarily during stress recovery phase.',
      },
      {
        publication: {
          pubmed_id: '30019436',
        },
        locus: 'AT3G24650',
        annotation:
          'Genetic and epigenetic essentials required for expression of the ABI3 gene, a crucial factor regulating dehydration stress signalling in Arabidopsis thaliana.',
      },
      {
        publication: {
          pubmed_id: '30908972',
        },
        locus: 'AT3G24650',
        annotation:
          'data suggest that BES1-mediated regulation of ABI3 is important in the reproductive phase transition of plants.',
      },
    ],
  },
}

export default a
