name: Build
on:
  push:
    branches-ignore:
      - main
      - staging
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - run: npm ci
      - run: npm run build
        env:
          BASE_URL: '/ePlant'
          VITE_MAPS_API_KEY: ${{ secrets.VITE_MAPS_API_KEY }}
